# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-27 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171126_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='favourite',
        ),
        migrations.AddField(
            model_name='user',
            name='favourite',
            field=models.ManyToManyField(related_name='_user_favourite_+', to='main.User'),
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
