# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-27 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171126_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoteby', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='favourite',
        ),
        migrations.AddField(
            model_name='quote',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoter', to='main.User'),
        ),
        migrations.AddField(
            model_name='quote',
            name='favourite',
            field=models.ManyToManyField(related_name='favor', to='main.User'),
        ),
    ]
